import { StyleSheet, Platform } from 'react-native';
import { AppColors } from '@/constants/theme';

export const makeStyles = (C: AppColors) => StyleSheet.create({
  scrollContent: {
    padding: 24,
    paddingBottom: 120,
  },
  pageTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    color: C.text,
    marginBottom: 24,
  },
  profileCard: {
    alignItems: 'center',
    backgroundColor: C.bgElement,
    borderRadius: 16,
    padding: 24,
    marginBottom: 28,
    borderWidth: 1,
    borderColor: C.border,
  },
  avatar: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: C.accent,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 4,
  },
  avatarText: {
    color: '#fff',
    fontSize: 26,
    fontWeight: 'bold',
  },
  avatarWrapper: {
    position: 'relative',
    marginBottom: 4,
  },
  avatarImage: {
    width: 72,
    height: 72,
    borderRadius: 36,
  },
  avatarLoadingOverlay: {
    position: 'absolute',
    top: 0, left: 0, right: 0, bottom: 0,
    borderRadius: 36,
    backgroundColor: 'rgba(0,0,0,0.5)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  changePhotoText: {
    color: C.accent,
    fontSize: 14,
    marginBottom: 12,
  },
  profileName: {
    color: C.text,
    fontSize: 20,
    fontWeight: '600',
    marginBottom: 4,
  },
  profileUsername: {
    color: C.textSecondary,
    fontSize: 15,
    marginBottom: 10,
  },
  adminBadge: {
    backgroundColor: C.accentBg,
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: C.accentBorder,
  },
  adminBadgeText: {
    color: C.accent,
    fontSize: 12,
    fontWeight: '600',
  },
  sectionLabel: {
    color: C.textMuted,
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    marginBottom: 8,
    marginLeft: 4,
  },
  sectionCard: {
    backgroundColor: C.bgElement,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: C.border,
    marginBottom: 28,
  },
  settingsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderRadius: 12,
  },
  settingsRowLabel: {
    color: C.text,
    fontSize: 16,
  },
  settingsRowRight: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    justifyContent: 'flex-end',
    gap: 6,
  },
  settingsRowValue: {
    color: C.textSecondary,
    fontSize: 15,
    maxWidth: '65%',
    textAlign: 'right',
  },
  settingsRowChevron: {
    color: C.textMuted,
    fontSize: 20,
    lineHeight: 22,
  },
  rowDivider: {
    height: 1,
    backgroundColor: C.border,
    marginLeft: 16,
  },
  // Theme selector
  themeSelector: {
    flexDirection: 'row',
    backgroundColor: C.bgElevated,
    borderRadius: 8,
    padding: 3,
    gap: 2,
  },
  themeOption: {
    flex: 1,
    paddingVertical: 7,
    borderRadius: 6,
    alignItems: 'center',
  },
  themeOptionActive: {
    backgroundColor: C.bgElement,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.15,
    shadowRadius: 2,
    elevation: 2,
  },
  themeOptionText: {
    fontSize: 13,
    fontWeight: '500',
    color: C.textSecondary,
  },
  themeOptionTextActive: {
    color: C.text,
    fontWeight: '600',
  },
  // Sign out
  signOutButton: {
    backgroundColor: C.destructiveBg,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: C.destructiveBorder,
    paddingVertical: 15,
    alignItems: 'center',
  },
  signOutText: {
    color: C.destructive,
    fontSize: 16,
    fontWeight: '600',
  },
  // Modals
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.7)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: C.bgElement,
    borderRadius: 16,
    padding: 24,
    width: '88%',
    borderWidth: 1,
    borderColor: C.borderMuted,
  },
  modalTitle: {
    color: C.text,
    fontSize: 18,
    fontWeight: '600',
    marginBottom: 16,
  },
  modalInput: {
    backgroundColor: C.bgInput,
    color: C.text,
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: C.borderMuted,
    fontSize: 16,
    marginBottom: 12,
  },
  modalInputMultiline: {
    height: 100,
    textAlignVertical: 'top',
  },
  modalActions: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 4,
  },
  modalCancelBtn: {
    flex: 1,
    backgroundColor: C.bgElevated,
    borderRadius: 8,
    paddingVertical: 12,
    alignItems: 'center',
  },
  modalCancelText: {
    color: C.textSecondary,
    fontSize: 15,
    fontWeight: '500',
  },
  modalSaveBtn: {
    flex: 1,
    backgroundColor: C.accent,
    borderRadius: 8,
    paddingVertical: 12,
    alignItems: 'center',
  },
  modalSaveText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '600',
  },
  // Switch (kept for re-use elsewhere)
  switchTrack: {
    width: 60,
    height: 34,
    borderRadius: 17,
    padding: 2,
    justifyContent: 'center',
  },
  thumb: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: 'white',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 4,
  },
  // Legacy (used by admin-panel styles that share this file)
  container: { padding: 20, paddingBottom: 100 },
  headerActionRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 },
  input: {
    backgroundColor: C.bgInput,
    color: C.text,
    padding: 12,
    borderRadius: 8,
    marginBottom: 15,
    borderWidth: 1,
    borderColor: C.borderMuted,
    fontSize: 16,
    ...Platform.select({
      ios: { shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.5, shadowRadius: 4 },
      android: { elevation: 3 },
    }),
  },
  button: { paddingVertical: 12, paddingHorizontal: 25, borderRadius: 8 },
  buttonText: { color: '#FFFFFF', fontSize: 18 },
  statusText: { marginBottom: 20, fontSize: 18, fontWeight: '600' },
});
