import { AppColors } from '@/constants/theme';
import { StyleSheet } from 'react-native';

export const makeStyles = (C: AppColors) =>
  StyleSheet.create({
    overlay: {
      flex: 1,
      justifyContent: 'flex-end',
      backgroundColor: 'rgba(0, 0, 0, 0.15)',
    },
    panel: {
      flex: 1,
      marginTop: 90,
      backgroundColor: C.profilePanelBg,
      borderTopLeftRadius: 36,
      borderTopRightRadius: 36,
      paddingTop: 28,
      paddingHorizontal: 24,
      alignItems: 'center',
    },
    closeButton: {
      position: 'absolute',
      top: 20,
      right: 20,
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: C.bgElevated,
      alignItems: 'center',
      justifyContent: 'center',
      zIndex: 10,
    },
    closeButtonText: {
      color: C.text,
      fontSize: 28,
      fontWeight: '700',
      lineHeight: 30,
    },
    scrollView: {
      width: '100%',
      flex: 1,
    },
    scrollContent: {
      width: '100%',
      alignItems: 'center',
      paddingTop: 28,
      paddingBottom: 50,
    },
    avatarCircle: {
      width: 110,
      height: 110,
      borderRadius: 55,
      backgroundColor: C.bgElement,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 4,
      borderColor: C.bgElement,
      overflow: 'hidden',
    },
    avatarImage: {
      width: '100%',
      height: '100%',
      borderRadius: 55,
    },
    initialsText: {
      color: '#fff',
      fontSize: 34,
      fontWeight: '900',
    },
    name: {
      fontSize: 34,
      fontWeight: '700',
      marginTop: 12,
      color: C.text,
      textAlign: 'center',
    },
    username: {
      fontSize: 20,
      color: C.textSecondary,
      marginBottom: 14,
      textAlign: 'center',
    },
    profileActionButton: {
      minWidth: 160,
      paddingVertical: 12,
      paddingHorizontal: 20,
      borderRadius: 20,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 22,
    },
    profileActionText: {
      color: '#fff',
      fontSize: 16,
      fontWeight: '800',
    },
    requestedButton: {
      minWidth: 160,
      paddingVertical: 12,
      paddingHorizontal: 20,
      borderRadius: 20,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 22,
      backgroundColor: C.bgElevated,
    },
    requestedText: {
      color: C.text,
      fontSize: 16,
      fontWeight: '800',
    },
    infoCard: {
      width: '100%',
      backgroundColor: C.profileCardBg,
      borderRadius: 24,
      padding: 20,
      marginBottom: 16,
    },
    cardTitle: {
      fontSize: 22,
      fontWeight: '700',
      marginBottom: 8,
      color: C.text,
    },
    cardText: {
      fontSize: 16,
      color: C.textSecondary,
      marginBottom: 4,
    },
    presenceBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingHorizontal: 12,
      paddingVertical: 5,
      borderRadius: 20,
      backgroundColor: C.bgElement,
      marginBottom: 16,
    },
    presenceDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
    },
    presenceText: {
      fontSize: 13,
      fontWeight: '600',
      color: C.textSecondary,
    },
    friendCountText: {
      width: '100%',
      fontSize: 20,
      fontWeight: '700',
      color: C.textSecondary,
      marginBottom: 14,
      marginTop: 4,
    },
    friendCard: {
      width: '100%',
      backgroundColor: C.profileCardBg,
      borderRadius: 28,
      paddingVertical: 12,
      paddingHorizontal: 16,
      marginBottom: 16,
    },
    friendRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 10,
    },
    friendAvatar: {
      width: 58,
      height: 58,
      borderRadius: 29,
      backgroundColor: C.bgElement,
      alignItems: 'center',
      justifyContent: 'center',
      overflow: 'hidden',
      marginRight: 14,
    },
    friendAvatarImage: {
      width: '100%',
      height: '100%',
    },
    friendInfo: {
      flex: 1,
      justifyContent: 'center',
    },
    friendName: {
      fontSize: 18,
      fontWeight: '700',
      color: C.text,
    },
    friendMeta: {
      fontSize: 13,
      fontWeight: '600',
      color: C.textSecondary,
      marginTop: 2,
    },
    smallAddButton: {
      minWidth: 76,
      paddingVertical: 9,
      paddingHorizontal: 12,
      borderRadius: 15,
      alignItems: 'center',
      justifyContent: 'center',
    },
    smallAddText: {
      color: '#fff',
      fontSize: 14,
      fontWeight: '800',
    },
    center: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: C.profilePanelBg,
      padding: 24,
    },
    message: {
      color: C.text,
      fontSize: 18,
      fontWeight: '700',
      textAlign: 'center',
      marginTop: 14,
    },
    requestedSmallButton: {
      minWidth: 92,
      paddingVertical: 9,
      paddingHorizontal: 12,
      borderRadius: 15,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: C.bgElevated,
    },
    requestedSmallText: {
      color: C.text,
      fontSize: 13,
      fontWeight: '800',
    },
    buttonRow: {
      flexDirection: 'row',
      gap: 10,
      marginBottom: 22,
    },
    messageButton: {
      paddingVertical: 10,
      paddingHorizontal: 20,
      borderRadius: 20,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1.5,
      borderColor: C.accent,
    },
    messageButtonText: {
      color: C.accent,
      fontSize: 15,
      fontWeight: '800',
    },
    reportButton: {
      paddingVertical: 10,
      paddingHorizontal: 20,
      borderRadius: 20,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1.5,
      borderColor: C.destructive,
    },
    reportButtonText: {
      color: C.destructive,
      fontSize: 15,
      fontWeight: '800',
    },
    reportModalOverlay: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: 'rgba(0,0,0,0.5)',
    },
    reportModalCard: {
      width: '85%',
      backgroundColor: C.bgElement,
      borderRadius: 24,
      padding: 24,
    },
    reportModalTitle: {
      fontSize: 22,
      fontWeight: '700',
      color: C.text,
      marginBottom: 16,
    },
    reportModalInput: {
      backgroundColor: C.bgInput,
      borderRadius: 12,
      padding: 14,
      fontSize: 16,
      color: C.text,
      minHeight: 100,
      textAlignVertical: 'top',
      borderWidth: 1,
      borderColor: C.border,
      marginBottom: 20,
    },
    reportModalActions: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
      gap: 20,
    },
    reportModalCancel: {
      fontSize: 16,
      fontWeight: '600',
      color: C.textSecondary,
      paddingVertical: 10,
    },
    reportModalSubmit: {
      fontSize: 16,
      fontWeight: '700',
      color: C.destructive,
      paddingVertical: 10,
    },
  });
